### ISSUE TITLE
Improve usage experience for use in local development

### ISSUE THREAD

**Issue by pksunkara** [neondatabase/neon#3747]
## Steps to reproduce

I have been wanting to use `neon` in my local development so that I can use the same environment if I want to use it in production. But, the current example for docker-compose file is too complex and has many unneeded parts.

## Expected result
Using neon locally should be as simple as:

```yaml
version: '3.7'
services:
    neon:
        image: neondatabase/neon
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - 55432:55432
```

Just like how an example is built in the [readme](https://github.com/neondatabase/neon#running-neon-database):

1. You shouldn't need multiple safekeepers since this is local.
2. You shouldn't need minio for object storage and rely on filesystem inside docker runtime.

## Actual result

Currently too complex.

## Logs, links
-
