### ISSUE TITLE
installation failed with docker-compose

### ISSUE THREAD

**Issue by liuyuanzhi-cn** [neondatabase/neon#3776]
I am trying to use docker-compose to install the neon database. Except for modifying the image source of [neon](https://registry.hub.docker.com/r/neondatabase/neon/tags) and [compute-node](https://registry.hub.docker.com/r/neondatabase/compute-node/tags) to the docker hub, the other content is the same as the [docker-compose.yml](https://github.com/neondatabase/neon/blob/main/docker-compose/docker-compose.yml) file and the [Dockerfile](https://github.com/neondatabase/neon/blob/main/docker-compose/compute_wrapper/Dockerfile) file. When I use the `docker-compose up` command to start these containers, the compute service has been restarting. It seems that the image on the docker hub is too old, if this is the reason, can anyone provide the latest version that can run successfully? Thank you. 

1. the modified  docker-compose.yml:

```yml
version: '3'

services:
  minio:
    restart: always
    image: quay.io/minio/minio:RELEASE.2022-10-20T00-55-09Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
    command: server /data --address :9000 --console-address ":9001"

  minio_create_buckets:
    image: minio/mc
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
    entrypoint:
      - "/bin/sh"
      - "-c"
    command:
      - "until (/usr/bin/mc alias set minio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD) do
             echo 'Waiting to start minio...' && sleep 1;
         done;
         /usr/bin/mc mb minio/neon --region=eu-north-1;
         exit 0;"
    depends_on:
      - minio

  pageserver:
    restart: always
#    image: ${REPOSITORY:-neondatabase}/neon:${TAG:-latest}
    image: neondatabase/neon:latest
    environment:
      - BROKER_ENDPOINT='http://storage_broker:50051'
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=password
      #- RUST_BACKTRACE=1
    ports:
       #- 6400:6400  # pg protocol handler
       - 9898:9898 # http endpoints
    entrypoint:
      - "/bin/sh"
      - "-c"
    command:
      - "/usr/local/bin/pageserver -D /data/.neon/
                                   -c \"broker_endpoint=$$BROKER_ENDPOINT\"
                                   -c \"listen_pg_addr='0.0.0.0:6400'\"
                                   -c \"listen_http_addr='0.0.0.0:9898'\"
                                   -c \"remote_storage={endpoint='http://minio:9000',
                                                        bucket_name='neon',
                                                        bucket_region='eu-north-1',
                                                        prefix_in_bucket='/pageserver/'}\""
    depends_on:
      - storage_broker
      - minio_create_buckets

  safekeeper1:
    restart: always
#    image: ${REPOSITORY:-neondatabase}/neon:${TAG:-latest}
    image: neondatabase/neon:latest
    environment:
      - SAFEKEEPER_ADVERTISE_URL=safekeeper1:5454
      - SAFEKEEPER_ID=1
      - BROKER_ENDPOINT=http://storage_broker:50051
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=password
      #- RUST_BACKTRACE=1
    ports:
      #- 5454:5454 # pg protocol handler
      - 7676:7676 # http endpoints
    entrypoint:
      - "/bin/sh"
      - "-c"
    command:
      - "safekeeper --listen-pg=$$SAFEKEEPER_ADVERTISE_URL
                    --listen-http='0.0.0.0:7676'
                    --id=$$SAFEKEEPER_ID
                    --broker-endpoint=$$BROKER_ENDPOINT
                    -D /data
                    --remote-storage=\"{endpoint='http://minio:9000',
                                        bucket_name='neon',
                                        bucket_region='eu-north-1',
                                        prefix_in_bucket='/safekeeper/'}\""
    depends_on:
      - storage_broker
      - minio_create_buckets

  safekeeper2:
    restart: always
#    image: ${REPOSITORY:-neondatabase}/neon:${TAG:-latest}
    image: neondatabase/neon:latest
    environment:
      - SAFEKEEPER_ADVERTISE_URL=safekeeper2:5454
      - SAFEKEEPER_ID=2
      - BROKER_ENDPOINT=http://storage_broker:50051
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=password
      #- RUST_BACKTRACE=1
    ports:
      #- 5454:5454 # pg protocol handler
      - 7677:7676 # http endpoints
    entrypoint:
      - "/bin/sh"
      - "-c"
    command:
      - "safekeeper --listen-pg=$$SAFEKEEPER_ADVERTISE_URL
                    --listen-http='0.0.0.0:7676'
                    --id=$$SAFEKEEPER_ID
                    --broker-endpoint=$$BROKER_ENDPOINT
                    -D /data
                    --remote-storage=\"{endpoint='http://minio:9000',
                                        bucket_name='neon',
                                        bucket_region='eu-north-1',
                                        prefix_in_bucket='/safekeeper/'}\""
    depends_on:
      - storage_broker
      - minio_create_buckets

  safekeeper3:
    restart: always
#    image: ${REPOSITORY:-neondatabase}/neon:${TAG:-latest}
    image: neondatabase/neon:latest
    environment:
      - SAFEKEEPER_ADVERTISE_URL=safekeeper3:5454
      - SAFEKEEPER_ID=3
      - BROKER_ENDPOINT=http://storage_broker:50051
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=password
      #- RUST_BACKTRACE=1
    ports:
      #- 5454:5454 # pg protocol handler
      - 7678:7676 # http endpoints
    entrypoint:
      - "/bin/sh"
      - "-c"
    command:
      - "safekeeper --listen-pg=$$SAFEKEEPER_ADVERTISE_URL
                    --listen-http='0.0.0.0:7676'
                    --id=$$SAFEKEEPER_ID
                    --broker-endpoint=$$BROKER_ENDPOINT
                    -D /data
                    --remote-storage=\"{endpoint='http://minio:9000',
                                        bucket_name='neon',
                                        bucket_region='eu-north-1',
                                        prefix_in_bucket='/safekeeper/'}\""
    depends_on:
      - storage_broker
      - minio_create_buckets

  storage_broker:
    restart: always
#    image: ${REPOSITORY:-neondatabase}/neon:${TAG:-latest}
    image: neondatabase/neon:latest
    ports:
      - 50051:50051
    command:
      - "storage_broker"
      - "--listen-addr=0.0.0.0:50051"

  compute:
    restart: always
    build:
      context: ./compute_wrapper/
      args:
#        - COMPUTE_IMAGE=compute-node-v${PG_VERSION:-14}
        - COMPUTE_IMAGE=compute-node
        - TAG=${TAG:-latest}
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
    environment:
      - PG_VERSION=${PG_VERSION:-14}
      #- RUST_BACKTRACE=1
    # Mount the test files directly, for faster editing cycle.
    volumes:
      - ./compute_wrapper/var/db/postgres/specs/:/var/db/postgres/specs/
      - ./compute_wrapper/shell/:/shell/
    ports:
      - 55433:55433 # pg protocol handler
      - 3080:3080 # http endpoints
    entrypoint:
      - "/shell/compute.sh"
    depends_on:
      - safekeeper1
      - safekeeper2
      - safekeeper3
      - pageserver

  compute_is_ready:
    image: postgres:latest
    entrypoint:
      - "/bin/bash"
      - "-c"
    command:
      - "until pg_isready -h compute -p 55433 ; do
            echo 'Waiting to start compute...' && sleep 1;
         done"
    depends_on:
      - compute

```

2. the modified Dockerfile:

```dockerfile
#ARG REPOSITORY=369495373322.dkr.ecr.eu-central-1.amazonaws.com
ARG REPOSITORY=neondatabase
#ARG COMPUTE_IMAGE=compute-node-v14
ARG COMPUTE_IMAGE=compute-node
ARG TAG=latest

FROM $REPOSITORY/${COMPUTE_IMAGE}:$TAG

USER root
RUN apt-get update &&       \
    apt-get install -y curl \
                       jq   \
                       netcat

USER postgres
```

3. error desc:

```shell
[root@localhost docker-compose]# docker container ls
CONTAINER ID   IMAGE                                              COMMAND                  CREATED          STATUS                          PORTS                                                               NAMES
20aa0601953c   postgres:latest                                    "/bin/bash -c 'until…"   10 minutes ago   Up 10 minutes                   5432/tcp                                                            docker-compose_compute_is_ready_1
6ea0e6c1545f   docker-compose_compute                             "/shell/compute.sh"      10 minutes ago   Restarting (1) 21 seconds ago                                                                       docker-compose_compute_1
c7f015eea81f   neondatabase/neon:latest                           "/bin/sh -c 'safekee…"   10 minutes ago   Up 10 minutes                   6400/tcp, 9898/tcp, 0.0.0.0:7677->7676/tcp, :::7677->7676/tcp       docker-compose_safekeeper2_1
c8267c261d4d   neondatabase/neon:latest                           "/bin/sh -c '/usr/lo…"   10 minutes ago   Up 10 minutes                   6400/tcp, 0.0.0.0:9898->9898/tcp, :::9898->9898/tcp                 docker-compose_pageserver_1
caeb1d5662ec   neondatabase/neon:latest                           "/bin/sh -c 'safekee…"   10 minutes ago   Up 10 minutes                   6400/tcp, 9898/tcp, 0.0.0.0:7676->7676/tcp, :::7676->7676/tcp       docker-compose_safekeeper1_1
937d5b4777ef   neondatabase/neon:latest                           "/bin/sh -c 'safekee…"   10 minutes ago   Up 10 minutes                   6400/tcp, 9898/tcp, 0.0.0.0:7678->7676/tcp, :::7678->7676/tcp       docker-compose_safekeeper3_1
45e511d097a1   quay.io/minio/minio:RELEASE.2022-10-20T00-55-09Z   "/usr/bin/docker-ent…"   10 minutes ago   Up 10 minutes                   0.0.0.0:9000-9001->9000-9001/tcp, :::9000-9001->9000-9001/tcp       docker-compose_minio_1
726c740c4c91   neondatabase/neon:latest                           "storage_broker --li…"   10 minutes ago   Up 10 minutes                   6400/tcp, 9898/tcp, 0.0.0.0:50051->50051/tcp, :::50051->50051/tcp   docker-compose_storage_broker_1
[root@localhost docker-compose]# docker-compose logs compute
WARNING: The http_proxy variable is not set. Defaulting to a blank string.
WARNING: The https_proxy variable is not set. Defaulting to a blank string.
Attaching to docker-compose_compute_1
compute_1               | exec /shell/compute.sh: no such file or directory
compute_1               | exec /shell/compute.sh: no such file or directory
compute_1               | exec /shell/compute.sh: no such file or directory
```
