### ISSUE TITLE
Local Neon database instance persistent storage

### ISSUE THREAD

**Issue by alexvuka1** [neondatabase/neon#5046]
Hello,

I used the example docker-compose setup to run Neon database locally. However, every time the containers restart all of the data is lost. Is there a way to configure it so that it persists?

Thanks!

**Comment by KyleXie** [comment]
I think I encountered the same problem.  It turns out they designed it like that. You can see it from the `docker-compose/compute_wrapper/shell/compute.sh`, each time you start a compute node, it creates a new tenant and a new timeline. If you prefer to persistent your data, you probably need to change the logic there. 

Plus, you may also want to map the data volume of your pageserver and safekeep to your disk, otherwise the data disappears after you recreate those docker containers.

**Comment by alexvuka1** [comment]
Thanks @KyleXie, I got it working. I modified `compute.sh` to
```bash
#!/bin/bash
set -eux

# Generate a random tenant or timeline ID
#
# Takes a variable name as argument. The result is stored in that variable.
generate_id() {
    local -n resvar=$1
    printf -v resvar '%08x%08x%08x%08x' $SRANDOM $SRANDOM $SRANDOM $SRANDOM
}

PG_VERSION=${PG_VERSION:-15}

SPEC_FILE_ORG=/var/db/postgres/specs/spec.json
SPEC_FILE=/tmp/spec.json

echo "Waiting pageserver become ready."
while ! nc -z pageserver 6400; do
     sleep 1;
done
echo "Page server is ready."

INFO_FILE=/shell/info.json
if [ -f "$INFO_FILE" ]; then
  echo "Info file exists, so reading from there"
  tenant_id=$(cat "$INFO_FILE" | jq -r '.tenantId')
  timeline_id=$(cat "$INFO_FILE" | jq -r '.timelineId')
  echo "{ \"tenantId\": \"${timeline_id}\", \"timelineId\": \"${timeline_id}\" }"
else
  echo "Create a tenant and timeline"
  generate_id tenant_id
  PARAMS=(
      -sb
      -X POST
      -H "Content-Type: application/json"
      -d "{\"new_tenant_id\": \"${tenant_id}\"}"
      http://pageserver:9898/v1/tenant/
  )
  result=$(curl "${PARAMS[@]}")
  echo $result | jq .

  generate_id timeline_id
  PARAMS=(
      -sb
      -X POST
      -H "Content-Type: application/json"
      -d "{\"new_timeline_id\": \"${timeline_id}\", \"pg_version\": ${PG_VERSION}}"
      "http://pageserver:9898/v1/tenant/${tenant_id}/timeline/"
  )
  result=$(curl "${PARAMS[@]}")
  echo $result | jq .

  echo "Save tenant id and timeline id locally"
  echo "{ \"tenantId\": \"${tenant_id}\", \"timelineId\": \"${timeline_id}\" }" > /shell/info.json
fi

echo "Overwrite tenant id and timeline id in spec file"
sed "s/TENANT_ID/${tenant_id}/" ${SPEC_FILE_ORG} > ${SPEC_FILE}
sed -i "s/TIMELINE_ID/${timeline_id}/" ${SPEC_FILE}

cat ${SPEC_FILE}

echo "Start compute node"
/usr/local/bin/compute_ctl --pgdata /var/db/postgres/compute \
     -C "postgresql://cloud_admin@localhost:55433/postgres"  \
     -b /usr/local/bin/postgres                              \
     -S ${SPEC_FILE}
```

And also the `docker-compose.yaml`
```yaml
version: '3'

services:
  minio:
    restart: always
    image: quay.io/minio/minio:RELEASE.2022-10-20T00-55-09Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
    command: server /data --address :9000 --console-address ":9001"
    volumes:
      - ./data:/data
...
```

This results in the data being persisted in the `data` directory and the tenant and timeline information in the `info.json` file
