### ISSUE TITLE
remote_storage_config deserialization does not reject unknown fields

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#8915]
# Context

This is punted from https://github.com/neondatabase/neon/pull/7656

# Problem

```toml
[remote_storage_config]
local_path = "/some/path"
some_invalid_field = 23
```

This deserializes without error.
It should not.

Had to comment out this test here:

https://github.com/neondatabase/neon/blob/b598782b430b4f301a9305b577e0771ca7f811fb/pageserver/src/config.rs#L608-L616

# Solution Proposal

Before jumping into fixing this, let's decide as a team on how important unknown fields are to us.
Maybe we can resolve this issue as "won't fix" and instead allow unknown fields:

https://github.com/neondatabase/neon/blob/b598782b430b4f301a9305b577e0771ca7f811fb/pageserver/src/config.rs#L549-L561
