### ISSUE TITLE
Investigate WAL ingest performance for logical messages

### ISSUE THREAD

**Issue by erikgrinaker** [neondatabase/neon#9642]
Ingestion of logical messages (noops) should be able to saturate the hardware, especially when fsync is disabled. It doesn't. Why?

See [Slack thread](https://neondb.slack.com/archives/C033RQ5SPDH/p1724933315325479) and [waltest.txt](https://github.com/user-attachments/files/17635056/waltest.txt).

**Comment by erikgrinaker** [comment]
Notes from initial tests (local with fsync disabled):

* WAL throughput caps out at ~300 MB/s, with ~1.2 GB/s disk throughput.
* `fio` can do sustained 5 GB/s writes with large enough block sizes (1M).
* Each append request results in an individual Safekeeper disk write.
* Each commit advancement results in a control file write and rename.
* Increasing logical messages from 10 KB to 1 MB did not significantly improve throughput.
* Increasing `MAX_SEND_SIZE` from 128 KB to 1 MB did not significantly improve throughput.

Interesting findings:

* Buffering/batching of `AppendRequest::wal_data` before dispatching writes significantly reduced throughput (below 100 MB/s).
* Disabling flush batching in WAL receiver significantly improved throughput to ~400 MB/s (i.e. don't use `NoFlushAppendRequest`).

I wonder if the delayed flushes due to the `NoFlushAppendRequest` batching causes delays in `commit_lsn` advancement, and this somehow affects the pipelining (similarly to the bandwidth-delay product). Will investigate.

**Comment by erikgrinaker** [comment]
Results of the `process_msg` and `wal_acceptor_throughput` benchmarks from #9531 with `fsync=false` on my local MacBook. This only measures payload throughput, and excludes segment/page/record/message headers.

```
process_msg/fsync=false/size=8
                        time:   [8.4812 µs 8.5148 µs 8.5460 µs]
                        thrpt:  [914.17 KiB/s 917.52 KiB/s 921.16 KiB/s]
process_msg/fsync=false/size=1024
                        time:   [9.4852 µs 9.5408 µs 9.5931 µs]
                        thrpt:  [101.80 MiB/s 102.36 MiB/s 102.96 MiB/s]
process_msg/fsync=false/size=8192
                        time:   [15.714 µs 16.296 µs 16.824 µs]
                        thrpt:  [464.36 MiB/s 479.41 MiB/s 497.17 MiB/s]
process_msg/fsync=false/size=131072
                        time:   [147.03 µs 153.72 µs 160.07 µs]
                        thrpt:  [780.93 MiB/s 813.19 MiB/s 850.15 MiB/s]
process_msg/fsync=false/size=1048576
                        time:   [1.3300 ms 1.3565 ms 1.3812 ms]
                        thrpt:  [723.99 MiB/s 737.21 MiB/s 751.90 MiB/s]

wal_acceptor_throughput/fsync=false/size=1024
                        time:   [14.618 s 14.714 s 14.828 s]
                        thrpt:  [69.058 MiB/s 69.591 MiB/s 70.049 MiB/s]
wal_acceptor_throughput/fsync=false/size=8192
                        time:   [3.3334 s 3.3466 s 3.3611 s]
                        thrpt:  [304.66 MiB/s 305.98 MiB/s 307.19 MiB/s]
wal_acceptor_throughput/fsync=false/size=131072
                        time:   [1.9624 s 1.9828 s 2.0100 s]
                        thrpt:  [509.46 MiB/s 516.44 MiB/s 521.82 MiB/s]
10wal_acceptor_throughput/fsync=false/size=1048576
                        time:   [1.9293 s 1.9515 s 1.9787 s]
                        thrpt:  [517.51 MiB/s 524.74 MiB/s 530.75 MiB/s]
```

Some findings:

* Raw `process_msg` caps out at ~800 MB/s. The disk can do 6 GB/s.
* There is a fixed cost of ~8 µs, or 125,000 messages/s.
  * At 8 KB/message, that's about 1 GB/s.
  * Comparing `size=1024` to `size=8192`, the additional IO cost is also about 8 µs.
  * The IO cost appears to scale linearly at about 1.2 µs/KB.
  * At 8 KB writes, optimizing or batching away the fixed cost would provide at most a 2x throughput improvement.
* The WAL acceptor loop reduces throughput from ~800 MB/s to ~500 MB/s, or ~40%, even at large message sizes. Why?

**Comment by erikgrinaker** [comment]
Adding another variant that also commits records doesn't show any significant difference. We only flush the control file after each WAL segment, so that checks out.

https://github.com/neondatabase/neon/blob/e287f36a058221b7c804b4b0f440933962eb3deb/safekeeper/src/safekeeper.rs#L931-L938

```
process_msg/fsync=false/commit=false/size=8
                        time:   [8.8677 µs 8.9545 µs 9.0712 µs]
                        thrpt:  [861.24 KiB/s 872.46 KiB/s 881.01 KiB/s]
process_msg/fsync=false/commit=false/size=1024
                        time:   [9.3791 µs 9.4232 µs 9.4647 µs]
                        thrpt:  [103.18 MiB/s 103.63 MiB/s 104.12 MiB/s]
process_msg/fsync=false/commit=false/size=8192
                        time:   [16.107 µs 16.785 µs 17.405 µs]
                        thrpt:  [448.86 MiB/s 465.45 MiB/s 485.02 MiB/s]
process_msg/fsync=false/commit=false/size=131072
                        time:   [153.33 µs 159.96 µs 166.16 µs]
                        thrpt:  [752.29 MiB/s 781.47 MiB/s 815.22 MiB/s]
process_msg/fsync=false/commit=false/size=1048576
                        time:   [1.3596 ms 1.3936 ms 1.4289 ms]
                        thrpt:  [699.83 MiB/s 717.57 MiB/s 735.51 MiB/s]

process_msg/fsync=false/commit=true/size=8
                        time:   [8.7410 µs 8.8093 µs 8.8824 µs]
                        thrpt:  [879.55 KiB/s 886.85 KiB/s 893.78 KiB/s]
process_msg/fsync=false/commit=true/size=1024
                        time:   [9.5369 µs 9.8461 µs 10.228 µs]
                        thrpt:  [95.479 MiB/s 99.183 MiB/s 102.40 MiB/s]
process_msg/fsync=false/commit=true/size=8192
                        time:   [15.810 µs 16.456 µs 17.041 µs]
                        thrpt:  [458.44 MiB/s 474.75 MiB/s 494.14 MiB/s]
process_msg/fsync=false/commit=true/size=131072
                        time:   [143.30 µs 154.28 µs 164.11 µs]
                        thrpt:  [761.67 MiB/s 810.21 MiB/s 872.30 MiB/s]
process_msg/fsync=false/commit=true/size=1048576
                        time:   [1.4108 ms 1.4383 ms 1.4624 ms]
                        thrpt:  [683.79 MiB/s 695.29 MiB/s 708.80 MiB/s]
```

**Comment by erikgrinaker** [comment]
The fixed 8 µs cost is likely Tokio scheduling overhead, see [flamegraph.svg](https://github.com/user-attachments/assets/1d03f161-6c63-4f1a-86e4-9088ad8ed8ea). Tokio's file IO is [not efficient](https://docs.rs/tokio/latest/tokio/fs/index.html#tuning-your-file-io). One option is to explore [tokio-epoll-uring](https://github.com/neondatabase/tokio-epoll-uring). Another is to increase batching along with [`tokio::fs::File::set_max_buf_size`](https://docs.rs/tokio/latest/i686-unknown-linux-gnu/tokio/fs/struct.File.html#method.set_max_buf_size) to amortize scheduling costs.

**Comment by erikgrinaker** [comment]
> Could be the segment size.

It's segments all right:

* https://github.com/neondatabase/neon/issues/9662
* https://github.com/neondatabase/neon/issues/9664
* https://github.com/neondatabase/neon/issues/9663

**Comment by erikgrinaker** [comment]
Much of the segment costs were addressed in the issues listed above. We can get further improvements by increasing the segment size in #9687, but this only yields 8% on the instances we currently use for Safekeepers.

Next, we should look at AppendRequest batching:

* #9689

**Comment by erikgrinaker** [comment]
With the above fixes, logical message throughput on a Safekeeper instance type has increased by 13% at 1 KB writes, and 246% at 1 MB writes. Batching of smaller writes will close the gap. We're maxing out at 734 MB/s, with a hardware capacity of 1.1 GB/s. 

```
wal_acceptor_throughput/fsync=true/commit=false/size=1024
                        time:   [25.490 s 25.558 s 25.621 s]
                        thrpt:  [39.968 MiB/s 40.065 MiB/s 40.172 MiB/s]
                 change:
                        time:   [-11.833% -11.444% -11.080%] (p = 0.00 < 0.05)
                        thrpt:  [+12.461% +12.923% +13.422%]

wal_acceptor_throughput/fsync=true/commit=false/size=8192
                        time:   [4.3186 s 4.3455 s 4.3710 s]
                        thrpt:  [234.27 MiB/s 235.65 MiB/s 237.11 MiB/s]
                 change:
                        time:   [-43.972% -43.545% -43.115%] (p = 0.00 < 0.05)
                        thrpt:  [+75.792% +77.133% +78.482%]

wal_acceptor_throughput/fsync=true/commit=false/size=131072
                        time:   [1.4305 s 1.4513 s 1.4727 s]
                        thrpt:  [695.30 MiB/s 705.57 MiB/s 715.84 MiB/s]
                 change:
                        time:   [-70.501% -70.069% -69.607%] (p = 0.00 < 0.05)
                        thrpt:  [+229.02% +234.10% +238.99%]

wal_acceptor_throughput/fsync=true/commit=false/size=1048576
                        time:   [1.3878 s 1.3951 s 1.4049 s]
                        thrpt:  [728.89 MiB/s 734.01 MiB/s 737.87 MiB/s]
                 change:
                        time:   [-71.279% -71.108% -70.884%] (p = 0.00 < 0.05)
                        thrpt:  [+243.45% +246.12% +248.17%]
```
